theme: jekyll-theme-minimal
title: Nikhita Vedula  <br>
description: <br> A computer scientist interested in data mining, natural language processing, and information retrieval. <br><br>
    <b>PhD</b>, Ohio State University (2020) <br>
                    <b>MS</b>, Ohio State University (2019) <br>
                    <b>B.Tech</b>, NIT-Nagpur, India (2015)
    <br><br> Contact:<a href="mailto:vedula.5@osu.edu"> vedula.5@osu.edu</a>. 
    <br> <br> <a href="https://scholar.google.com/citations?user=TgJ5r14AAAAJ&hl=en"> <font color="red"> Google Scholar </font> </a> 
    <br> <br> <a href="https://www.linkedin.com/in/nikhita-vedula-7228036a/"> <font color="red"> LinkedIn </font> </a> 
logo: nv.jpeg
auto_ids: true

